"""
Untitled Project - Generated by PyDesigner
https://pydesigner.qzz.io

This code uses PyQt5. To use PySide6 instead, replace:
  from PyQt5.QtWidgets import ... -> from PySide6.QtWidgets import ...
  from PyQt5.QtCore import ... -> from PySide6.QtCore import ...
  from PyQt5.QtGui import ... -> from PySide6.QtGui import ...
  app.exec_() -> app.exec()

Required libraries:
pip install PyQt5
"""
from functools import partial
import sys
from Piano import Piano
from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QWidget, QPushButton, QLabel,
    QLineEdit, QFrame, QCheckBox, QRadioButton, QComboBox,
    QTextEdit, QButtonGroup, QListWidget, QGraphicsView, QGraphicsScene
)
from PyQt5.QtCore import Qt, QByteArray
from PyQt5.QtGui import QFont, QIcon, QPixmap, QImage


class App(QMainWindow):
    

    
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Untitled Project")
        self.setGeometry(100, 100, 800, 600)
        
        self.incx=1
        # Central widget
        self.central_widget = QWidget()
        self.setCentralWidget(self.central_widget)
        self.filename=""
        # Create widgets
        self._create_widgets()
        
    def _create_widgets(self):
        """Create and place all widgets"""
        
        # button_1
        
        
        self.BPlay = QPushButton("Play", self.central_widget)
        self.BPlay.setGeometry(660, 40, 120, 36)
        self.BPlay.setFont(QFont("Arial", 12))
        self.BPlay.setStyleSheet("background-color: #3b82f6; color: #ffffff;")
        self.BPlay.clicked.connect(self.Play)
        
        # entry_1  
        self.sheet_input = QLineEdit(self.central_widget)
        self.sheet_input.setGeometry(10, 40, 130, 40)
        self.sheet_input.setPlaceholderText("Enter text...")
        self.sheet_input.setFont(QFont("Arial", 12))
        
        # textarea_1
        self.label_1 = QLabel("Enter filename of Excel Sheet Music and hit play", self.central_widget)
        self.label_1.setGeometry(200, 40, 400, 80)
        self.label_1.setFont(QFont("Arial", 12))
        self.label_1.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        self.label_1.setStyleSheet("background-color: #ffffff; color: #000000;")
        self.label_1.setWordWrap(True)
    # ==========================================
    # Event Handlers - Implement your logic here
    # ==========================================
 
        
        
    
    def Play(self):
        """
        Handle HW event
        TODO: Implement your logic here
        """
        
        P=Piano(self.sheet_input.text())
        P.sheetgen()
        P.audgen()
        P.play()
    
   
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = App()
    window.show()     
   # P=Piano("UTS.xlsx")
   # P.sheetgen()
  #  P.audgen()
    #P.play()
    sys.exit(app.exec_())
